services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - frontend/.env
    volumes:
     # Volume pour le hot reload en développement
      - ./frontend/index.html:/app/frontend/index.html
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
      - ./frontend/vite.config.ts:/app/frontend/vite.config.ts
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/backend/src
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 