GET http://localhost:3000/api/categories

###

GET http://localhost:3000/api/categories/1


###

POST http://localhost:3000/api/categories 
Content-Type: application/json

{
    "name": "Avion"
}

### 

PUT http://localhost:3000/api/categories/2
Content-Type: application/json

{
    "name": "Vélo"
}

###

DELETE http://localhost:3000/api/categories/5