/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdsAdIdImport } from './routes/ads.$adId'

// Create Virtual Routes

const VelosLazyImport = createFileRoute('/velos')()
const VehiculesLazyImport = createFileRoute('/vehicules')()
const VacancesLazyImport = createFileRoute('/vacances')()
const TelephonieLazyImport = createFileRoute('/telephonie')()
const SportLazyImport = createFileRoute('/sport')()
const ServicesLazyImport = createFileRoute('/services')()
const PhotographieLazyImport = createFileRoute('/photographie')()
const OutillageLazyImport = createFileRoute('/outillage')()
const InformatiqueLazyImport = createFileRoute('/informatique')()
const HabillementLazyImport = createFileRoute('/habillement')()
const ElectromenagerLazyImport = createFileRoute('/electromenager')()
const BebeLazyImport = createFileRoute('/bebe')()
const AmeublementLazyImport = createFileRoute('/ameublement')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const VelosLazyRoute = VelosLazyImport.update({
  path: '/velos',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/velos.lazy').then((d) => d.Route))

const VehiculesLazyRoute = VehiculesLazyImport.update({
  path: '/vehicules',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/vehicules.lazy').then((d) => d.Route))

const VacancesLazyRoute = VacancesLazyImport.update({
  path: '/vacances',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/vacances.lazy').then((d) => d.Route))

const TelephonieLazyRoute = TelephonieLazyImport.update({
  path: '/telephonie',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/telephonie.lazy').then((d) => d.Route))

const SportLazyRoute = SportLazyImport.update({
  path: '/sport',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sport.lazy').then((d) => d.Route))

const ServicesLazyRoute = ServicesLazyImport.update({
  path: '/services',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/services.lazy').then((d) => d.Route))

const PhotographieLazyRoute = PhotographieLazyImport.update({
  path: '/photographie',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/photographie.lazy').then((d) => d.Route))

const OutillageLazyRoute = OutillageLazyImport.update({
  path: '/outillage',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/outillage.lazy').then((d) => d.Route))

const InformatiqueLazyRoute = InformatiqueLazyImport.update({
  path: '/informatique',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/informatique.lazy').then((d) => d.Route))

const HabillementLazyRoute = HabillementLazyImport.update({
  path: '/habillement',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/habillement.lazy').then((d) => d.Route))

const ElectromenagerLazyRoute = ElectromenagerLazyImport.update({
  path: '/electromenager',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/electromenager.lazy').then((d) => d.Route),
)

const BebeLazyRoute = BebeLazyImport.update({
  path: '/bebe',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bebe.lazy').then((d) => d.Route))

const AmeublementLazyRoute = AmeublementLazyImport.update({
  path: '/ameublement',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ameublement.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AdsAdIdRoute = AdsAdIdImport.update({
  path: '/ads/$adId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/ameublement': {
      id: '/ameublement'
      path: '/ameublement'
      fullPath: '/ameublement'
      preLoaderRoute: typeof AmeublementLazyImport
      parentRoute: typeof rootRoute
    }
    '/bebe': {
      id: '/bebe'
      path: '/bebe'
      fullPath: '/bebe'
      preLoaderRoute: typeof BebeLazyImport
      parentRoute: typeof rootRoute
    }
    '/electromenager': {
      id: '/electromenager'
      path: '/electromenager'
      fullPath: '/electromenager'
      preLoaderRoute: typeof ElectromenagerLazyImport
      parentRoute: typeof rootRoute
    }
    '/habillement': {
      id: '/habillement'
      path: '/habillement'
      fullPath: '/habillement'
      preLoaderRoute: typeof HabillementLazyImport
      parentRoute: typeof rootRoute
    }
    '/informatique': {
      id: '/informatique'
      path: '/informatique'
      fullPath: '/informatique'
      preLoaderRoute: typeof InformatiqueLazyImport
      parentRoute: typeof rootRoute
    }
    '/outillage': {
      id: '/outillage'
      path: '/outillage'
      fullPath: '/outillage'
      preLoaderRoute: typeof OutillageLazyImport
      parentRoute: typeof rootRoute
    }
    '/photographie': {
      id: '/photographie'
      path: '/photographie'
      fullPath: '/photographie'
      preLoaderRoute: typeof PhotographieLazyImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesLazyImport
      parentRoute: typeof rootRoute
    }
    '/sport': {
      id: '/sport'
      path: '/sport'
      fullPath: '/sport'
      preLoaderRoute: typeof SportLazyImport
      parentRoute: typeof rootRoute
    }
    '/telephonie': {
      id: '/telephonie'
      path: '/telephonie'
      fullPath: '/telephonie'
      preLoaderRoute: typeof TelephonieLazyImport
      parentRoute: typeof rootRoute
    }
    '/vacances': {
      id: '/vacances'
      path: '/vacances'
      fullPath: '/vacances'
      preLoaderRoute: typeof VacancesLazyImport
      parentRoute: typeof rootRoute
    }
    '/vehicules': {
      id: '/vehicules'
      path: '/vehicules'
      fullPath: '/vehicules'
      preLoaderRoute: typeof VehiculesLazyImport
      parentRoute: typeof rootRoute
    }
    '/velos': {
      id: '/velos'
      path: '/velos'
      fullPath: '/velos'
      preLoaderRoute: typeof VelosLazyImport
      parentRoute: typeof rootRoute
    }
    '/ads/$adId': {
      id: '/ads/$adId'
      path: '/ads/$adId'
      fullPath: '/ads/$adId'
      preLoaderRoute: typeof AdsAdIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/ameublement': typeof AmeublementLazyRoute
  '/bebe': typeof BebeLazyRoute
  '/electromenager': typeof ElectromenagerLazyRoute
  '/habillement': typeof HabillementLazyRoute
  '/informatique': typeof InformatiqueLazyRoute
  '/outillage': typeof OutillageLazyRoute
  '/photographie': typeof PhotographieLazyRoute
  '/services': typeof ServicesLazyRoute
  '/sport': typeof SportLazyRoute
  '/telephonie': typeof TelephonieLazyRoute
  '/vacances': typeof VacancesLazyRoute
  '/vehicules': typeof VehiculesLazyRoute
  '/velos': typeof VelosLazyRoute
  '/ads/$adId': typeof AdsAdIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/ameublement': typeof AmeublementLazyRoute
  '/bebe': typeof BebeLazyRoute
  '/electromenager': typeof ElectromenagerLazyRoute
  '/habillement': typeof HabillementLazyRoute
  '/informatique': typeof InformatiqueLazyRoute
  '/outillage': typeof OutillageLazyRoute
  '/photographie': typeof PhotographieLazyRoute
  '/services': typeof ServicesLazyRoute
  '/sport': typeof SportLazyRoute
  '/telephonie': typeof TelephonieLazyRoute
  '/vacances': typeof VacancesLazyRoute
  '/vehicules': typeof VehiculesLazyRoute
  '/velos': typeof VelosLazyRoute
  '/ads/$adId': typeof AdsAdIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/ameublement': typeof AmeublementLazyRoute
  '/bebe': typeof BebeLazyRoute
  '/electromenager': typeof ElectromenagerLazyRoute
  '/habillement': typeof HabillementLazyRoute
  '/informatique': typeof InformatiqueLazyRoute
  '/outillage': typeof OutillageLazyRoute
  '/photographie': typeof PhotographieLazyRoute
  '/services': typeof ServicesLazyRoute
  '/sport': typeof SportLazyRoute
  '/telephonie': typeof TelephonieLazyRoute
  '/vacances': typeof VacancesLazyRoute
  '/vehicules': typeof VehiculesLazyRoute
  '/velos': typeof VelosLazyRoute
  '/ads/$adId': typeof AdsAdIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ameublement'
    | '/bebe'
    | '/electromenager'
    | '/habillement'
    | '/informatique'
    | '/outillage'
    | '/photographie'
    | '/services'
    | '/sport'
    | '/telephonie'
    | '/vacances'
    | '/vehicules'
    | '/velos'
    | '/ads/$adId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ameublement'
    | '/bebe'
    | '/electromenager'
    | '/habillement'
    | '/informatique'
    | '/outillage'
    | '/photographie'
    | '/services'
    | '/sport'
    | '/telephonie'
    | '/vacances'
    | '/vehicules'
    | '/velos'
    | '/ads/$adId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ameublement'
    | '/bebe'
    | '/electromenager'
    | '/habillement'
    | '/informatique'
    | '/outillage'
    | '/photographie'
    | '/services'
    | '/sport'
    | '/telephonie'
    | '/vacances'
    | '/vehicules'
    | '/velos'
    | '/ads/$adId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  AmeublementLazyRoute: typeof AmeublementLazyRoute
  BebeLazyRoute: typeof BebeLazyRoute
  ElectromenagerLazyRoute: typeof ElectromenagerLazyRoute
  HabillementLazyRoute: typeof HabillementLazyRoute
  InformatiqueLazyRoute: typeof InformatiqueLazyRoute
  OutillageLazyRoute: typeof OutillageLazyRoute
  PhotographieLazyRoute: typeof PhotographieLazyRoute
  ServicesLazyRoute: typeof ServicesLazyRoute
  SportLazyRoute: typeof SportLazyRoute
  TelephonieLazyRoute: typeof TelephonieLazyRoute
  VacancesLazyRoute: typeof VacancesLazyRoute
  VehiculesLazyRoute: typeof VehiculesLazyRoute
  VelosLazyRoute: typeof VelosLazyRoute
  AdsAdIdRoute: typeof AdsAdIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  AmeublementLazyRoute: AmeublementLazyRoute,
  BebeLazyRoute: BebeLazyRoute,
  ElectromenagerLazyRoute: ElectromenagerLazyRoute,
  HabillementLazyRoute: HabillementLazyRoute,
  InformatiqueLazyRoute: InformatiqueLazyRoute,
  OutillageLazyRoute: OutillageLazyRoute,
  PhotographieLazyRoute: PhotographieLazyRoute,
  ServicesLazyRoute: ServicesLazyRoute,
  SportLazyRoute: SportLazyRoute,
  TelephonieLazyRoute: TelephonieLazyRoute,
  VacancesLazyRoute: VacancesLazyRoute,
  VehiculesLazyRoute: VehiculesLazyRoute,
  VelosLazyRoute: VelosLazyRoute,
  AdsAdIdRoute: AdsAdIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/ameublement",
        "/bebe",
        "/electromenager",
        "/habillement",
        "/informatique",
        "/outillage",
        "/photographie",
        "/services",
        "/sport",
        "/telephonie",
        "/vacances",
        "/vehicules",
        "/velos",
        "/ads/$adId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/ameublement": {
      "filePath": "ameublement.lazy.tsx"
    },
    "/bebe": {
      "filePath": "bebe.lazy.tsx"
    },
    "/electromenager": {
      "filePath": "electromenager.lazy.tsx"
    },
    "/habillement": {
      "filePath": "habillement.lazy.tsx"
    },
    "/informatique": {
      "filePath": "informatique.lazy.tsx"
    },
    "/outillage": {
      "filePath": "outillage.lazy.tsx"
    },
    "/photographie": {
      "filePath": "photographie.lazy.tsx"
    },
    "/services": {
      "filePath": "services.lazy.tsx"
    },
    "/sport": {
      "filePath": "sport.lazy.tsx"
    },
    "/telephonie": {
      "filePath": "telephonie.lazy.tsx"
    },
    "/vacances": {
      "filePath": "vacances.lazy.tsx"
    },
    "/vehicules": {
      "filePath": "vehicules.lazy.tsx"
    },
    "/velos": {
      "filePath": "velos.lazy.tsx"
    },
    "/ads/$adId": {
      "filePath": "ads.$adId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
