GET http://localhost:3000/api/ads

###

GET http://localhost:3000/api/ads/3

###

GET http://localhost:3000/api/ads?category_ids=1,3

###

GET http://localhost:3000/api/ads/avg_price/3

###

POST http://localhost:3000/api/ads 
Content-Type: application/json

{
    "title": "Bike to sell",
    "description": "My bike is red, working fine.",
    "owner": "sten@gmail.com",
    "price": 50,
    "picture": "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
    "location": "Paris",
    "category_id": 1
}

### 

PUT http://localhost:3000/api/ads/2
Content-Type: application/json

{
    "title": "Bike remplacé",
    "description": "My bike is red, working fine.",
    "owner": "toto@gmail.com",
    "price": 2000,
    "picture": "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
    "location": "Nantes",
    "category_id": "1"
}

### 

PATCH http://localhost:3000/api/ads/3
Content-Type: application/json

{
    "title": "Changement titre"
}

###

### 

DELETE http://localhost:3000/api/ads/3

### 

DELETE http://localhost:3000/api/ads